DROP TABLE IF EXISTS TRAINEESHIP_DB.USER;
CREATE TABLE TRAINEESHIP_DB.USER (
USER_ID INT AUTO_INCREMENT NOT NULL,
LOGIN VARCHAR(30) UNIQUE NOT NULL,
PASSWORD VARCHAR(30) NOT NULL,
EMAIL VARCHAR(30) UNIQUE NOT NULL,
FIRST_NAME VARCHAR(30) NOT NULL,
LAST_NAME VARCHAR(30) NOT NULL,
BIRTH_DAY DATE NOT NULL,
ROLE_ID INT NOT NULL,
PRIMARY KEY (USER_ID),
FOREIGN KEY (ROLE_ID) REFERENCES TRAINEESHIP_DB.ROLE (ROLE_ID) ON DELETE CASCADE
ON UPDATE CASCADE
);